-- RoundWise v0.5: add tee-level par, yardage, course rating and slope.
create table if not exists public.course_tees (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete cascade,
  course_key text not null,
  tee_name text not null,
  par integer,
  total_yardage integer,
  rating numeric,
  slope integer check (slope between 55 and 155),
  is_default boolean not null default false,
  source_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(course_id, tee_name)
);

alter table public.rounds add column if not exists tee_par integer;
alter table public.rounds add column if not exists tee_yardage integer;
alter table public.rounds add column if not exists course_rating numeric;
alter table public.rounds add column if not exists course_slope integer;

do $$ begin
  if not exists (select 1 from pg_trigger where tgname = 'course_tees_updated_at') then
    create trigger course_tees_updated_at before update on public.course_tees for each row execute function public.set_updated_at();
  end if;
end $$;

alter table public.course_tees enable row level security;
drop policy if exists "Read public or owned course tees" on public.course_tees;
drop policy if exists "Insert owned course tees" on public.course_tees;
drop policy if exists "Update owned course tees" on public.course_tees;
drop policy if exists "Delete owned course tees" on public.course_tees;
create policy "Read public or owned course tees" on public.course_tees for select using (
  exists (select 1 from public.courses c where c.id = course_id and (c.is_public or c.owner_id = auth.uid()))
);
create policy "Insert owned course tees" on public.course_tees for insert with check (
  owner_id = auth.uid() and exists (select 1 from public.courses c where c.id = course_id and c.owner_id = auth.uid())
);
create policy "Update owned course tees" on public.course_tees for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "Delete owned course tees" on public.course_tees for delete using (owner_id = auth.uid());

insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('35b14ae9-33bf-5044-8968-16ceea3d0d81','d16e9c62-613b-546a-be9c-711032e9b12b',null,'Applewood Golf Course','Black',71,5992,67.4,112,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/applewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('575a221e-2711-5795-979d-e855225562a9','d16e9c62-613b-546a-be9c-711032e9b12b',null,'Applewood Golf Course','Silver - Ladies',71,5376,69.0,118,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/applewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('287371a0-a40b-5c9a-8fd0-df62d6f7b960','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Black Bear',70,6636,71.7,137,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('54d3cf5e-e2e0-52f1-adfc-137e37ed5043','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Arrowhead',70,6302,70.0,136,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('c65609c7-5147-5033-aaa7-d30529a7ac10','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Arrowhead - Ladies',72,6302,76.1,147,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('7b4f8095-cae6-556f-b253-2bca73bd236e','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Silver Fox',70,5902,68.4,128,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('41cdf818-b87d-582c-ba60-188e247db54b','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Silver Fox - Ladies',72,5902,73.8,143,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('60f3a7ce-711b-5eec-bac8-a1a0709e1b8d','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Columbine',70,5338,65.9,119,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('6f865167-53b3-5251-bc34-041047c3893a','12836297-d455-589a-af74-baa5ac5bbdbe',null,'Arrowhead Golf Club','Columbine - Ladies',72,5338,71.5,132,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/arrowhead_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('1a9bdb16-4f75-55e6-8437-6b1a8f99c071','e7a73aec-d012-5cca-819b-15e3b3e65133',null,'Broken Tee Golf Course — Championship 18','Blue',72,6995,71.7,130,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/broken_tee_englewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('4faa0cce-200a-5460-973b-f57248bbffa4','e7a73aec-d012-5cca-819b-15e3b3e65133',null,'Broken Tee Golf Course — Championship 18','White',72,6492,69.2,125,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/broken_tee_englewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('aaabf192-e7ab-520d-be19-23f248820f7a','e7a73aec-d012-5cca-819b-15e3b3e65133',null,'Broken Tee Golf Course — Championship 18','White - Ladies',72,6492,76.0,140,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/broken_tee_englewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('6687d123-335d-58f6-abd7-e20f91c67603','e7a73aec-d012-5cca-819b-15e3b3e65133',null,'Broken Tee Golf Course — Championship 18','Gold',72,5934,67.1,114,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/broken_tee_englewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('289ee99d-a0fd-534b-b57c-38bcbb63d6c7','e7a73aec-d012-5cca-819b-15e3b3e65133',null,'Broken Tee Golf Course — Championship 18','Gold - Ladies',72,5934,72.7,136,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/broken_tee_englewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('70ff80fd-d091-5cf6-9022-0b7a9db8507a','e7a73aec-d012-5cca-819b-15e3b3e65133',null,'Broken Tee Golf Course — Championship 18','Red - Ladies',72,5413,69.9,127,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/broken_tee_englewood_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('f04d1b8e-858b-540d-999a-d32650d8809a','b72e59b8-460a-51f6-b06a-1d932106eb01',null,'City Park Golf Course','White',72,6318,68.6,117,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/city_park_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('992a5d65-f0e7-5a1c-9bce-722d1e119428','b72e59b8-460a-51f6-b06a-1d932106eb01',null,'City Park Golf Course','Red - Ladies',74,6181,74.1,116,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/city_park_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('6e292fd3-86bc-54af-8b2c-1435763a2dfc','c9e62a3f-610a-5efa-8241-7af9d364fe67',null,'Evergreen Golf Course','Black',69,5374,69.6,125,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/evergreen_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('bd295209-ca04-5e05-a363-3135a2346b62','c9e62a3f-610a-5efa-8241-7af9d364fe67',null,'Evergreen Golf Course','White',69,5001,65.8,119,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/evergreen_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('3579ab27-4c81-5796-943e-50d8fe429700','c9e62a3f-610a-5efa-8241-7af9d364fe67',null,'Evergreen Golf Course','Blue',69,4877,62.4,111,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/evergreen_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('d06f44e1-91b4-5def-af4c-d117717fcd03','c9e62a3f-610a-5efa-8241-7af9d364fe67',null,'Evergreen Golf Course','Red - Ladies',69,4723,65.4,119,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/evergreen_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('98575ef4-d579-53c5-b0aa-a794ea483967','aef0300a-9234-53b9-9442-0420b84aa107',null,'Foothills Golf Course — Championship 18','Championship',72,6922,71.5,127,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/foothills_golf_course_denver/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('657c4d84-f23b-5113-b86b-faf67be2bbc5','aef0300a-9234-53b9-9442-0420b84aa107',null,'Foothills Golf Course — Championship 18','Middle',72,6339,69.4,120,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/foothills_golf_course_denver/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('b24a1458-727b-5411-94c6-26c850179e51','aef0300a-9234-53b9-9442-0420b84aa107',null,'Foothills Golf Course — Championship 18','Forward - Ladies',72,5841,70.2,126,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/foothills_golf_course_denver/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('cc7f0510-4e2a-583b-9ad7-aa40471d593d','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Black',72,6831,72.5,139,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('8a5a8758-f7bc-5930-9191-bf6e8a964c41','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','T-Rex',72,6577,71.2,135,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('0aad958c-1fcd-5201-b3e2-0e02080bccbc','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Blue',72,6241,69.3,131,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('7d767d03-8f17-54b7-8846-c4ae09e32afc','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Blue - Ladies',72,6241,75.0,146,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('293b60f0-564b-56d9-90b0-b65e58f28ede','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Trike',72,5933,68.3,124,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('f3f59e06-c8b8-528f-8a32-1f8233036f89','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Trike - Ladies',72,5933,73.1,146,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('9df4ec48-e2d5-5317-80bc-9310dbf3527f','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','White',72,5559,66.4,119,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('944296cc-3f64-5eb5-90e4-d13c96e722a7','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','White - Ladies',72,5559,71.9,136,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('71a67081-78cf-552e-97e0-f3c6e14738ed','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Palm - Ladies',72,5197,69.3,133,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('b9922b47-0b84-5872-b9a7-5b9938878746','b2c5ae26-c0cc-5dc6-8223-dea903dfc5ed',null,'Fossil Trace Golf Club','Gold - Ladies',72,4681,66.5,121,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/fossil_trace_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('8421e3ea-b05e-570b-aea4-4a5b35611ef6','872c5d96-9517-5bfa-8717-c0ae019956b9',null,'Highlands Ranch Golf Club','Irwin',72,7179,71.6,130,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/highlands_ranch_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('7eb42146-cd8a-5937-9e55-55abcaab4000','872c5d96-9517-5bfa-8717-c0ae019956b9',null,'Highlands Ranch Golf Club','Blue',72,6719,69.5,126,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/highlands_ranch_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('1c3068f1-bcc7-5c82-a428-ee9ffe29be10','872c5d96-9517-5bfa-8717-c0ae019956b9',null,'Highlands Ranch Golf Club','Regular',72,6311,67.3,122,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/highlands_ranch_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('a2592881-29e6-5ab2-8a93-f8015d0ce5ce','872c5d96-9517-5bfa-8717-c0ae019956b9',null,'Highlands Ranch Golf Club','Regular - Ladies',72,6311,74.7,137,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/highlands_ranch_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('9ab38bad-93dd-5c72-bd5f-1bbcbe4aa30a','872c5d96-9517-5bfa-8717-c0ae019956b9',null,'Highlands Ranch Golf Club','Forward - Ladies',72,5340,69.2,124,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/highlands_ranch_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('9b951b00-b7a4-56b3-88fa-0db2acabfece','a7ec2c55-c6a1-51b3-b5d5-21c4219c12c5',null,'Lone Tree Golf Club','Gold',72,7054,73.1,139,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/lone_tree_golf_club_hotel/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('8e72ef85-f13a-59ed-9f44-57ef060fd252','a7ec2c55-c6a1-51b3-b5d5-21c4219c12c5',null,'Lone Tree Golf Club','Blue',72,6490,70.5,126,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/lone_tree_golf_club_hotel/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('2e93d206-d481-5cf2-8660-ee273ba76032','a7ec2c55-c6a1-51b3-b5d5-21c4219c12c5',null,'Lone Tree Golf Club','White',72,5951,68.2,123,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/lone_tree_golf_club_hotel/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('fcb39d89-61c9-5654-967b-8abb0c054151','a7ec2c55-c6a1-51b3-b5d5-21c4219c12c5',null,'Lone Tree Golf Club','White - Ladies',72,5951,73.4,140,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/lone_tree_golf_club_hotel/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('6f4c4a58-127b-5015-bad5-9b8d28f5845d','a7ec2c55-c6a1-51b3-b5d5-21c4219c12c5',null,'Lone Tree Golf Club','Red - Ladies',72,5288,71.0,129,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/lone_tree_golf_club_hotel/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('923d8001-bc8c-51f7-aa59-43e086ae7309','23c1205d-4401-5eb6-971f-217f934c98df',null,'Overland Park Golf Course','White',72,6676,68.5,113,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/overland_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('aabfbabd-7332-59b2-877d-e5422a120206','23c1205d-4401-5eb6-971f-217f934c98df',null,'Overland Park Golf Course','Red - Ladies',74,6097,72.7,123,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/overland_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('84694515-f542-5225-8cb0-b0f1a997bf62','1b30f968-df7c-506e-96bd-e06ac3cbcf38',null,'Raccoon Creek Golf Course','Black',72,7045,73.3,131,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/raccoon_creek_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('49ca3085-37d9-523a-a919-b8d1c901c298','1b30f968-df7c-506e-96bd-e06ac3cbcf38',null,'Raccoon Creek Golf Course','Blue',72,6737,71.3,126,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/raccoon_creek_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('da78c49f-d720-5a8b-99e7-fd791888ffb8','1b30f968-df7c-506e-96bd-e06ac3cbcf38',null,'Raccoon Creek Golf Course','White',72,6054,67.7,120,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/raccoon_creek_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('434d6e6a-3e4a-53e4-9ab9-20802e236b21','1b30f968-df7c-506e-96bd-e06ac3cbcf38',null,'Raccoon Creek Golf Course','White - Ladies',72,6054,72.3,131,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/raccoon_creek_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('1cc14624-266c-5d9a-9ea5-5f2f7be55bb8','1b30f968-df7c-506e-96bd-e06ac3cbcf38',null,'Raccoon Creek Golf Course','Red - Ladies',72,5130,68.2,125,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/raccoon_creek_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('79424c35-13f9-5941-b013-87f27ea34109','9b343995-7600-565c-a56e-24e48cb90b53',null,'South Suburban Golf Course — Regulation 18','Black',72,6793,70.1,122,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/south_suburban_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('e61806ea-d5c6-564e-89d2-6b30bb91f13a','9b343995-7600-565c-a56e-24e48cb90b53',null,'South Suburban Golf Course — Regulation 18','Blue',72,6263,68.4,116,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/south_suburban_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('c43e6dec-c471-588c-89dd-d77390565c69','9b343995-7600-565c-a56e-24e48cb90b53',null,'South Suburban Golf Course — Regulation 18','White - Ladies',72,5638,71.2,123,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/south_suburban_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('f9d1e679-d9e6-57ae-9875-85eca04a0bd9','9b343995-7600-565c-a56e-24e48cb90b53',null,'South Suburban Golf Course — Regulation 18','Red - Ladies',72,5274,69.3,119,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/south_suburban_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('2670fa89-4cc8-5399-a5f4-2ad7498b18dc','e7fd3ab4-acd8-52aa-89a6-a0f3951d1b4e',null,'The Golf Club at Bear Dance','Professional',72,7726,74.0,141,false,'https://www.greenskeeper.org/colorado/denver_east_west_south/bear_dance_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('7516edbf-9824-5931-817e-2f36bbeeabe2','e7fd3ab4-acd8-52aa-89a6-a0f3951d1b4e',null,'The Golf Club at Bear Dance','Black',72,7344,72.0,137,false,'https://www.greenskeeper.org/colorado/denver_east_west_south/bear_dance_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('1fd5bd2d-c471-5557-a9c5-b087fb7e0018','e7fd3ab4-acd8-52aa-89a6-a0f3951d1b4e',null,'The Golf Club at Bear Dance','Blue',72,6879,69.8,128,false,'https://www.greenskeeper.org/colorado/denver_east_west_south/bear_dance_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('99c62aca-b069-5774-b0ab-ab0798739473','e7fd3ab4-acd8-52aa-89a6-a0f3951d1b4e',null,'The Golf Club at Bear Dance','White',72,6293,67.2,124,true,'https://www.greenskeeper.org/colorado/denver_east_west_south/bear_dance_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('3c527921-62c5-5b83-a39e-27bffdc04c6b','e7fd3ab4-acd8-52aa-89a6-a0f3951d1b4e',null,'The Golf Club at Bear Dance','Gold',72,5240,63.4,110,false,'https://www.greenskeeper.org/colorado/denver_east_west_south/bear_dance_golf_club/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('13673c28-f78c-5c84-a34d-e04c073220b9','2f2f841d-14bf-5c00-9440-84688bd24852',null,'The Meadows Golf Club','Gold',72,7011,72.2,135,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/the_meadows_golf_club_littleton/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('21f3720f-07ca-5158-be77-f7f43570d241','2f2f841d-14bf-5c00-9440-84688bd24852',null,'The Meadows Golf Club','Blue',72,6558,69.8,132,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/the_meadows_golf_club_littleton/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('a6249374-762b-54b9-b73c-739e7b4bdf10','2f2f841d-14bf-5c00-9440-84688bd24852',null,'The Meadows Golf Club','White',72,6112,67.5,127,true,'https://www.greenskeeper.org/colorado/Denver_East_West_South/the_meadows_golf_club_littleton/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('3a1af12d-a3e6-5b43-a34d-2e5b2597aeee','2f2f841d-14bf-5c00-9440-84688bd24852',null,'The Meadows Golf Club','Red - Ladies',72,5437,71.1,124,false,'https://www.greenskeeper.org/colorado/Denver_East_West_South/the_meadows_golf_club_littleton/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('bcab60fb-fc59-58a2-9878-271c5d14fab6','970aee82-7be7-5eb7-926d-b5424224468e',null,'Wellshire Golf Course','Blue',71,6498,71.1,129,false,'https://greenskeeper.org/colorado/Denver_East_West_South/wellshire_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('2c89fadc-7f1f-5df9-9777-a24baa7037dd','970aee82-7be7-5eb7-926d-b5424224468e',null,'Wellshire Golf Course','White',71,6232,70.7,127,true,'https://greenskeeper.org/colorado/Denver_East_West_South/wellshire_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
insert into public.course_tees (id,course_id,owner_id,course_key,tee_name,par,total_yardage,rating,slope,is_default,source_url) values ('f3d74b2e-5746-557b-84a0-14b6e91fff5f','970aee82-7be7-5eb7-926d-b5424224468e',null,'Wellshire Golf Course','Red - Ladies',73,4900,71.2,129,false,'https://greenskeeper.org/colorado/Denver_East_West_South/wellshire_golf_course/scorecard.cfm') on conflict (course_id,tee_name) do update set par=excluded.par,total_yardage=excluded.total_yardage,rating=excluded.rating,slope=excluded.slope,is_default=excluded.is_default,source_url=excluded.source_url;
